### PR TITLE
[#IONFRA-69] Devops project for io-service-metadata

### PR DESCRIPTION
**Pull request by uolter**
- It creates beand new project with a sole pipeline 
- Already applied

### CODE REVIEW

**Comment by pasqualedevita** [comment]
@Undermaken can u check if pipeline start on pull requests and merge on master? thanks

**Review by pasqualedevita — APPROVED** [review]
LGTM

**Comment by Undermaken** [comment]
> @Undermaken can u check if pipeline start on pull requests and merge on master? thanks
@pasqualedevita 
I opened a new pull request for test azure pipeline
It seems nothing changed, it still doesn't work

**Comment by pasqualedevita** [comment]
@uolter I added this config to trigger pipeline on merge to master

```
  ci_trigger {
    override {
      batch                            = false
      max_concurrent_builds_per_branch = 1
      polling_interval                 = 0
      branch_filter {
        exclude = []
        include = [var.io-services-metadata.repository.branch_name]
      }
      path_filter {
        exclude = []
        include = []
      }
    }
  }
```

for `pull_request_trigger` it's correct use `include = [var.io-services-metadata.repository.branch_name]` that it's default configuration for all pipeline in this repo

@Undermaken when u want we can try a deploy with a merge in master :)

**Comment by pasqualedevita** [comment]
Deploy ok, thanka @Undermaken @uolter

**Review by pasqualedevita — APPROVED** [review]

**Pull request merged**
